-- Table Candidate --
DROP TABLE CANDIDATE IF EXISTS;
CREATE TABLE CANDIDATE(
    ID_CANDIDATE INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_BA1E630F_F19E_49AD_89C3_AA37FAF93483) NOT NULL AUTO_INCREMENT,
    CANDIDATE_NAME VARCHAR(20) NOT NULL,
    CONSTRAINT CONSTRAINT_C PRIMARY KEY (ID_CANDIDATE)
);
CREATE UNIQUE INDEX CONSTRAINT_INDEX_C ON CANDIDATE (CANDIDATE_NAME);
CREATE UNIQUE INDEX PRIMARY_KEY_C ON CANDIDATE (ID_CANDIDATE);

-- Table User --
DROP TABLE USER IF EXISTS;
CREATE TABLE USER(
    ID_USER INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_27EF15EF_E1ED_411D_8F8E_48E5D599B334) NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL,
    CODE_LOGIN VARCHAR(200) NOT NULL,
    SENT_CODELOGIN BOOLEAN DEFAULT 0 NOT NULL,
    LOGIN_DONE BOOLEAN DEFAULT 0 NOT NULL,
    SENT_FORMDATA BOOLEAN DEFAULT 0 NOT NULL,
    CONSTRAINT CONSTRAINT_2 PRIMARY KEY (EMAIL)
);
CREATE UNIQUE INDEX PRIMARY_KEY_27 ON "USER" (EMAIL);
CREATE UNIQUE INDEX USER_ID_USER_UINDEX ON "USER" (ID_USER);

-- Table Allowed_Email --
DROP TABLE ALLOWED_EMAIL IF EXISTS ;
CREATE TABLE ALLOWED_EMAIL (
    ID_ALLOWEDEMAIL INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D3D32FF8_C04F_4383_882B_740871859D4E) NOT NULL AUTO_INCREMENT,
    EMAIL_USER VARCHAR(20) NOT NULL,
    CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID_ALLOWEDEMAIL),
    CONSTRAINT CONSTRAINT_84 FOREIGN KEY (EMAIL_USER) REFERENCES "USER"(EMAIL) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX CONSTRAINT_84_INDEX_9 ON ALLOWED_EMAIL (EMAIL_USER);
CREATE UNIQUE INDEX PRIMARY_KEY_9 ON ALLOWED_EMAIL (ID_ALLOWEDEMAIL);

-- Table Score --
DROP TABLE SCORE IF EXISTS;
CREATE TABLE SCORE (
    ID_SCORE INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EEBEE504_6A30_40F2_8811_1BD53CFE1B24) NOT NULL AUTO_INCREMENT,
    CANDIDATE_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID_SCORE),
    CONSTRAINT CONSTRAINT_4B FOREIGN KEY (CANDIDATE_NAME) REFERENCES CANDIDATE(CANDIDATE_NAME) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX CONSTRAINT_4B_INDEX_A ON SCORE (CANDIDATE_NAME);
CREATE UNIQUE INDEX PRIMARY_KEY_A ON SCORE (ID_SCORE);
